### ISSUE TITLE
Can't use the chat console

### ISSUE THREAD

**Issue by leonardocustodio** [paschmann/rasa-ui#112]
Hi,

I was not able to test the Rasa UI yet, every time I try to use the console I get this error:

`Cache Not Found for Agent. Making a DB call for: dialogue
Agent Information: []
DB Error while getting agent details.
TypeError: Cannot read property 'agent_id' of undefined
    at /var/www/laura-assistant/server/routes/middleware.js:41:37
    at tryCatcher (/var/www/laura-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/laura-assistant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/laura-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/laura-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/laura-assistant/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/laura-assistant/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/laura-assistant/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/laura-assistant/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

`

Looks like it is not finding the Agent. Don't really know why. I got no error when running the app with npm start.

**Comment by yuxuan2015** [comment]
@leonardocustodio Is your problem solved?
