### ISSUE TITLE
Error in training

### ISSUE THREAD

**Issue by Lejla1979** [paschmann/rasa-ui#142]
Hi, after I create agent in RASA_UI and start to run it, I got message: 
2019-01-05 09:30:41+0100 [-] Unhandled Error
        Traceback (most recent call last):
          File "C:\Users\Lejla\python36\lib\site-packages\rasa_nlu\server.py", l
ine 142, in decorated
            return f(*args, **kwargs)
          File "C:\Users\Lejla\python36\lib\site-packages\rasa_nlu\server.py", l
ine 125, in decorated
            return f(*args, **kwargs)
          File "C:\Users\Lejla\python36\lib\site-packages\twisted\internet\defer
.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "C:\Users\Lejla\python36\lib\site-packages\twisted\internet\defer
.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "C:\Users\Lejla\python36\lib\site-packages\twisted\internet\defer
.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "C:\Users\Lejla\python36\lib\site-packages\rasa_nlu\server.py", l
ine 353, in train
            data_file = dump_to_data_file(data)
          File "C:\Users\Lejla\python36\lib\site-packages\rasa_nlu\server.py", l
ine 171, in dump_to_data_file
            return utils.create_temporary_file(data_string, "_training_data")
          File "C:\Users\Lejla\python36\lib\site-packages\rasa_nlu\utils\__init_
_.py", line 345, in create_temporary_file
            f.write(data)
          File "C:\Users\Lejla\python36\lib\tempfile.py", line 485, in func_wrap
per
            return func(*args, **kwargs)
          File "C:\Users\Lejla\python36\lib\encodings\cp1252.py", line 19, in en
code
            return codecs.charmap_encode(input,self.errors,encoding_table)[0]
        builtins.UnicodeEncodeError: 'charmap' codec can't encode character '\u2
265' in position 127580: character maps to <undefined>

**Comment by Lejla1979** [comment]
Any help?
