### ISSUE TITLE
Server Crash on Rasa core POST request

### ISSUE THREAD

**Issue by aryadegari** [paschmann/rasa-ui#143]
I ran the whole stack using `docker-compose up` command.
When I enable Rasa-core for a bot and then test it with a message, rasa ui crashes. here is error log
```rasa_ui_1        | Got to parse middleware
[{"agent_id":2,"agent_name":"Arash","endpoint_enabled":false,"endpoint_url":null,"basic_auth_username":null,"basic_auth_password":null,"rasa_core_enabled":true}]
rasa_ui_1        | Messages.createUserMessage
rasa_ui_1        | routeRequest
rasa_ui_1        | Rasa Core Parse Request -> http://rasa_core:5005/conversations/admin/parse
rasa_ui_1        | Create Initial cache for rasa Core Parse Request
rasa_ui_1        | Message created successfully!!!
rasa_ui_1        | After request:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
rasa_ui_1        | <title>404 Not Found</title>
rasa_ui_1        | <h1>Not Found</h1>
rasa_ui_1        | <p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
rasa_ui_1        | 
rasa_ui_1        | undefined:1
rasa_ui_1        | <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
rasa_ui_1        | ^
rasa_ui_1        | 
rasa_ui_1        | SyntaxError: Unexpected token < in JSON at position 0
rasa_ui_1        |     at JSON.parse (<anonymous>)
rasa_ui_1        |     at Request._callback (/opt/rasaui/server/routes/mw_routes/core_router.js:108:24)
rasa_ui_1        |     at Request.self.callback (/opt/rasaui/node_modules/request/request.js:185:22)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at Request.<anonymous> (/opt/rasaui/node_modules/request/request.js:1161:10)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at IncomingMessage.<anonymous> (/opt/rasaui/node_modules/request/request.js:1083:12)
rasa_ui_1        |     at Object.onceWrapper (events.js:273:13)
rasa_ui_1        |     at IncomingMessage.emit (events.js:187:15)
rasa_ui_1        |     at endReadableNT (_stream_readable.js:1094:12)
rasa_ui_1        |     at process._tickCallback (internal/process/next_tick.js:63:19)
rasa_ui_1        | npm ERR! code ELIFECYCLE
rasa_ui_1        | npm ERR! errno 1
rasa_ui_1        | npm ERR! RasaUI@2.3.2 start: `node server/server.js`
rasa_ui_1        | npm ERR! Exit status 1
rasa_ui_1        | npm ERR! 
rasa_ui_1        | npm ERR! Failed at the RasaUI@2.3.2 start script.
rasa_ui_1        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rasa_ui_1        | 
rasa_ui_1        | npm ERR! A complete log of this run can be found in:
rasa_ui_1        | npm ERR!     /home/rasaui/.npm/_logs/2019-01-08T15_01_59_590Z-debug.log
```
It is stated in [Migration Guide](https://rasa.com/docs/core/migrations/#http-server-endpoints) that `/parse` endpoint is removed in 0.11.0 version.

This issue was also reported in #122.

**Comment by elvay1** [comment]
Hi @aryadegari, you should try the rasa-ui_v2 branch, which handle rasa Core >= 0.11.

**Comment by aryadegari** [comment]
Thank you for your response. 
So in docker compose of rasa-ui_v2 branch `image: paschmann/rasa-ui:latest` should be changed to `image: paschmann/rasa-ui:rasa-ui_v2`. 

I made this change but now it has another error: 
```
rasa_ui_1        | Messages.createUserMessage
rasa_ui_1        | routeRequest
rasa_ui_1        | Rasa Core Version Request -> http://rasa_core:5005/version
rasa_ui_1        | /opt/rasaui/server/routes/mw_routes/core_server_v12.js:38
rasa_ui_1        |                     body.forEach(function(element) {
rasa_ui_1        |                          ^
rasa_ui_1        | 
rasa_ui_1        | TypeError: body.forEach is not a function
rasa_ui_1        |     at Request._callback (/opt/rasaui/server/routes/mw_routes/core_server_v12.js:38:26)
rasa_ui_1        |     at Request.self.callback (/opt/rasaui/node_modules/request/request.js:185:22)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at Request.<anonymous> (/opt/rasaui/node_modules/request/request.js:1161:10)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at IncomingMessage.<anonymous> (/opt/rasaui/node_modules/request/request.js:1083:12)
rasa_ui_1        |     at Object.onceWrapper (events.js:273:13)
rasa_ui_1        |     at IncomingMessage.emit (events.js:187:15)
rasa_ui_1        |     at endReadableNT (_stream_readable.js:1094:12)
rasa_ui_1        |     at process._tickCallback (internal/process/next_tick.js:63:19)
rasa_ui_1        | npm ERR! code ELIFECYCLE
rasa_ui_1        | npm ERR! errno 1
rasa_ui_1        | npm ERR! RasaUI@2.3.2 start: `node server/server.js`
rasa_ui_1        | npm ERR! Exit status 1
rasa_ui_1        | npm ERR! 
rasa_ui_1        | npm ERR! Failed at the RasaUI@2.3.2 start script.
rasa_ui_1        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rasa_ui_1        | 
rasa_ui_1        | npm ERR! A complete log of this run can be found in:
rasa_ui_1        | npm ERR!     /home/rasaui/.npm/_logs/2019-01-15T10_44_17_224Z-debug.log
```

**Comment by huberrom** [comment]
Can you try to change the variable "rasacorerequestpath" in your Dockerfile from rasacorerequestpath from /conversations/{id}/parse to /conversations/{id}/respond ?

If you use a docker-compose, you can change it by adding it directly on your docker-compose.yml

``` rasa_ui:
    image: rasa-ui:rasa-ui_v2
    environment:
      rasacorerequestpath: "/conversations/{id}/respond "```

**Comment by aryadegari** [comment]
I added `rasacorerequestpath` environment variable. 
now it returns nlu connection error:
```
rasa_ui_1        | Messages.createUserMessage
rasa_ui_1        | routeRequest
rasa_ui_1        | Rasa Core Version Request -> http://rasa_core:5005/version
rasa_core_1      | 172.18.0.6 - - [2019-01-15 13:48:05] "POST /conversations/admin/respond HTTP/1.1" 200 110 0.008076
rasa_core_1      | 172.18.0.6 - - [2019-01-15 13:58:05] "GET /version HTTP/1.1" 200 167 0.000863
rasa_core_1      | 2019-01-15 13:58:05 ERROR    rasa_core.interpreter  - Failed to parse text 'hi' using rasa NLU over http. Error: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /parse?model=nlu&project=current&q=hi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ffa8863a4e0>: Failed to establish a new connection: [Errno 111] Connection refused',))
rasa_ui_1        | Message created successfully!!!
```

**Comment by huberrom** [comment]
I think this error is linked to rasa core / rasa nlu and not Rasa UI.

Try to send a request to this endpoint (/conversations/admin/respond) using postman or curl, you should have the same issue.

**Comment by aryadegari** [comment]
here is curl request and it's response which is an empty array.

request:
`curl -XGET http://localhost:5005/conversations/admin/respond?query=hi`

response:
`[]`

**Comment by huberrom** [comment]
Isn't respond a POST request ?

**Comment by aryadegari** [comment]
I used the request mentioned in [core docs](https://rasa.com/docs/core/server/#operation/respond) which is a GET request with `query` parameter.

It is also mentioned that this api is deprecated and `/webhooks/rest/webhook` should be used instead.

**Comment by bamania8** [comment]
> here is curl request and it's response which is an empty array.
> 
> request:
> `curl -XGET http://localhost:5005/conversations/admin/respond?query=hi`
> 
> response:
> `[]`

I guess ...here instead of hi ...you need to pass the specific Intent , which have hi as the customer input .

**ex. curl -XGET http://localhost:5005/conversations/admin/respond?query=greet**

**Comment by huberrom** [comment]
If you use the intent, you have to send with / ex query=/greet

But the bot should respond without the name of the specific intent

**Comment by bamania8** [comment]
> If you use the intent, you have to send with / ex query=/greet
> 
> But the bot should respond without the name of the specific intent

I tried without "/" and it worked . 
------------------------------------------------------
**root@rasa:/home/rasaui# curl -XGET http://192.168.15.98:5005/conversations/admin/respond?query=greet
[{"recipient_id":"admin","text":"Hey! How are you?"}]**
-----------------------------------------------------------------------

Ya but it worked for couple of times only with same intent...then I had to restart core.run.

My query is ...If I want to Integrate with core ...then Do I need to again clone the git of v2.0 and then 
modify the rasacorerequestpath value. Note : I'm running rasaui using npm and core("0.12.2"

) is on another server

**Comment by pradeepmvn** [comment]
This has been merged to master. The latest build should have a test page to test your bot. Please make sure  rasa core is enabled with REST Channel and enable http api flag  ```--enable_api ```. Feel free to open another issue if you still have it.
