### ISSUE TITLE
Getting error while configuring NLU  "GET /config HTTP/1.1" 404 342 0.000402  also No Project or model directory getting created.

### ISSUE THREAD

**Issue by bamania8** [paschmann/rasa-ui#144]
Rasa NLU Train Request -> http://localhost:5000/train?project=Rohit
{ ip_address: '::ffff:192.168.15.98',
  query: '/api/v2/rasa/train?name=Rohit_20190122-140437&project=Rohit',
  event_type: 'train',
  event_data:
   { project: 'Rohit',
     model: 'Rohit_20190122-140437',
     data: { rasa_nlu_data: [Object] } } }
Training Done !! Response Code : 200

=============================================

INFO:root:Starting model training
INFO:root:Training process <Process(Process-2, started)> started
127.0.0.1 - - [2019-01-22 14:04:37] "POST /train?project=Rohit&model=Rohit_20190122-140437 HTTP/1.1" 200 218 0.034997
INFO:root:Training data format at /tmp/tmpl58t53mp_training_data.json is rasa_nlu
WARNING:py.warnings:/usr/local/lib/python3.6/dist-packages/rasa_nlu/training_data.py:118: UserWarning: Intent 'greets' has only 1 training examples! minimum is 2, training may fail.
  warnings.warn(template.format(intent, size, self.MIN_EXAMPLES_PER_INTENT))

INFO:root:Training data stats:
        - intent examples: 1 (1 distinct intents)
        - found intents: greets
        - entity examples: 0 (0 distinct entities)
        - found entities:

Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/train.py", line 73, in do_train
    interpreter = trainer.train(training_data)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/model.py", line 138, in train
    components.validate_arguments(self.pipeline, self.config)
  File "/usr/local/lib/python3.6/dist-packages/rasa_nlu/components.py", line 114, in validate_arguments
    "The `backend` configuration key is NOT supported anymore.")
ValueError: Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.The `backend` configuration key is NOT supported anymore.

**Comment by bamania8** [comment]
Was trying to run with NLU version 0.8.4 on another server. Which may not have /config option . Update NLU version and started NLU server with proper options and now it's working.
