### ISSUE TITLE
Config file error

### ISSUE THREAD

**Issue by OwaisRaza1** [paschmann/rasa-ui#203]
I am facing issue when I run rasa UI with nlu server, when I start rasa UI and it hits to the nlu server at port 5000 it throws following exception:

[5860] [ERROR] Exception occurred while handling uri: 'http://localhost:5000/config'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 893, in handle_request
handler, args, kwargs, uri = self.router.get(request)
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 407, in get
return self._get(request.path, request.method, "")
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 469, in _get
raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /config not found

Unable to find its solution can you please help ???

**Comment by paschmann** [comment]
Hi @OwaisRaza1 - please check out the v3 branch of Rasa UI - the /config path was removed from Rasa and is no longer valid which was causing that issue.
