### ISSUE TITLE
http://localhost:5001/api/v2/rasa/status

### ISSUE THREAD

**Issue by dayastark** [paschmann/rasa-ui#212]
Hi Sir,

Am working on Rasa-UI, but whenever I try to train & try to doing highlight entities from given user inputs, it will goes. Console window showing following error.

```

2019-09-11 06:08:03.382|rasa-ui|info|Rasa NLU Status Request -> http://10.211.55.8:5005/status;
2019-09-11 06:08:03.881|rasa-ui|info|Rasa Response: undefined;
2019-09-11 06:08:03.890|rasa-ui|info|The first argument must be one of type string or Buffer. Received type undefined;
_http_outgoing.js:470
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.writeHead (_http_server.js:232:21)
    at sendOutput (D:\demo\rasa-ui\server\routes\rasa_router.js:164:9)
    at Request._callback (D:\demo\rasa-ui\server\routes\rasa_router.js:155:9)
    at self.callback (D:\demo\rasa-ui\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (D:\demo\rasa-ui\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RasaUI@3.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RasaUI@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dayai\AppData\Roaming\npm-cache\_logs\2019-09-11T06_08_03_960Z-debug.log
```

And I got this error also

```
http://localhost:5001/api/v2/rasa/status
This site can’t be reached
```
`2019-09-11 06:16:06.354|rasa-ui|info|Rasa Server: http://10.211.55.8:5005;
2019-09-11 06:16:06.355|rasa-ui|info|--> Unable to connect to Rasa Server: Error: ETIMEDOUT;`

**Comment by paschmann** [comment]
Hi @dayastark - You need to set the IP/DNS of your Rasa server in the package.json file.

**Comment by paschmann** [comment]
Issue fixed.
