### ISSUE TITLE
Issue in starting RASA UI

### ISSUE THREAD

**Issue by Prskriti** [paschmann/rasa-ui#226]
On running command npm start getting type error on terminal side:

(base) INHYKPMAC01-MacBook-Pro:rasa-ui prakriti$ npm start

> RasaUI@3.0.1 start /Users/prakriti/Documents/rasa_bot/rasa-ui
> node server/server.js

/Users/prakriti/Documents/rasa_bot/rasa-ui/server/server.js:65
    'Rasa UI Server: http://localhost:' + listener.address().port
                                                            ^

TypeError: Cannot read property 'port' of null
    at checkRasaUI (/Users/prakriti/Documents/rasa_bot/rasa-ui/server/server.js:65:61)
    at Object.<anonymous> (/Users/prakriti/Documents/rasa_bot/rasa-ui/server/server.js:60:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! RasaUI@3.0.1 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RasaUI@3.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prakriti/.npm/_logs/2019-11-13T11_43_13_078Z-debug.log

**Comment by davidjeevan** [comment]
you solved that issue ?
