### ISSUE TITLE
Console errors on fresh install

### ISSUE THREAD

**Issue by johngriffin** [paschmann/rasa-ui#23]
*Steps to replicate*
* Do a fresh install of rasa-ui and rasa-nlu as per the installation instructions
* Train a model with the [tutorial data](http://rasa-nlu.readthedocs.io/en/latest/tutorial.html)
* Check that Rasa NLU is responding as expected on port 5000
`curl -XPOST localhost:5000/parse -d '{"q":"I am looking for Chinese food"}' | python -mjson.tool`
* Update package.json in rasaui to point to localhost:5000 for rasa and update postgres string
* Open http://localhost:5001/ 
* Log in to UI with admin:admin

*Observed*
* Everything looks correct in the UI, on the dashboard page is says "1 available model"
* Trying to click on almost any button causes errors in the console though, mostly 500s. 
* If you just stay on the dashboard page you'll get the following errors in the console:  (added a screenshot as it's easier to read)
<img width="1222" alt="screen shot 2017-11-01 at 15 38 43" src="https://user-images.githubusercontent.com/273591/32282909-d29e300a-bf1a-11e7-86ad-3dbab40f679f.png">

`:5001/#!/agent/add:1 Failed to decode downloaded font: http://localhost:5001/assets/css/fonts/Simple-Line-Icons.woff2?v=2.4.0
:5001/#!/agent/add:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
:5001/#!/agent/add:1 Failed to decode downloaded font: http://localhost:5001/assets/css/fonts/fontawesome-webfont.woff2?v=4.6.3
:5001/#!/agent/add:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
:5001/#!/agent/add:1 Failed to decode downloaded font: http://localhost:5001/assets/css/fonts/fontawesome-webfont.woff?v=4.6.3
:5001/#!/agent/add:1 OTS parsing error: incorrect file size in WOFF header
settings Failed to load resource: the server responded with a status of 500 (unknown)
angular.js:14525 Possibly unhandled rejection: {"data":{"status":"error","message":"Invalid status code: 0"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/v2/settings","params":{},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTA5NTQ5NDUyfQ.NwOc99QG1YsPXDXptk93j9oJAiHAyqWgbNiLqhCJILc"}},"statusText":"unknown"}
(anonymous) @ angular.js:14525
(anonymous) @ angular.js:11008
g @ angular.js:16860
$digest @ angular.js:17971
$apply @ angular.js:18269
l @ angular.js:12387
A.onload @ angular.js:12541
intent_usage_total Failed to load resource: the server responded with a status of 500 (unknown)
angular.js:14525 Possibly unhandled rejection: {"data":{"status":"error","message":"Invalid status code: 0"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/v2/intent_usage_total","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTA5NTQ5NDUyfQ.NwOc99QG1YsPXDXptk93j9oJAiHAyqWgbNiLqhCJILc"}},"statusText":"unknown"}
(anonymous) @ angular.js:14525
(anonymous) @ angular.js:11008
g @ angular.js:16860
$digest @ angular.js:17971
$apply @ angular.js:18269
l @ angular.js:12387
A.onload @ angular.js:12541
request_usage_total Failed to load resource: the server responded with a status of 500 (unknown)
angular.js:14525 Possibly unhandled rejection: {"data":{"status":"error","message":"Invalid status code: 0"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/v2/request_usage_total","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTA5NTQ5NDUyfQ.NwOc99QG1YsPXDXptk93j9oJAiHAyqWgbNiLqhCJILc"}},"statusText":"unknown"}
(anonymous) @ angular.js:14525
(anonymous) @ angular.js:11008
g @ angular.js:16860
$digest @ angular.js:17971
$apply @ angular.js:18269
l @ angular.js:12387
A.onload @ angular.js:12541
avg_intent_usage_by_day Failed to load resource: the server responded with a status of 500 (unknown)
angular.js:14525 Possibly unhandled rejection: {"data":{"status":"error","message":"Invalid status code: 0"},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/api/v2/avg_intent_usage_by_day","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTA5NTQ5NDUyfQ.NwOc99QG1YsPXDXptk93j9oJAiHAyqWgbNiLqhCJILc"}},"statusText":"unknown"}`

**Comment by pradeepmvn** [comment]
@johngriffin Do you see any errors on the Console of node.js server? It shows something wrong with the server and got and internal error. I suspect Database connection URL might be wrong.

**Comment by johngriffin** [comment]
Ok, it looks like some of this was caused by my postgres user not having all privileges.  I've now done:

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO rasaui;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA rasaui TO rasaui;

The errors when visiting the dashboard have disappeared now however I'm still getting in the terminal that's running rasa-ui when I use the RH pane to run a simple query - screenshot of this attached.

`
Create Initial cache
Object Inserted into Cache
Agent Information: []
DB Error while getting agent details.
TypeError: Cannot read property 'agent_id' of undefined
    at /Users/john/dev/rasa/rasaui/server/routes/middleware.js:215:48
    at NodeCache.module.exports.NodeCache.get (/Users/john/dev/rasa/rasaui/node_modules/node-cache/lib/node_cache.js:101:11)
    at NodeCache.get (/Users/john/dev/rasa/rasaui/node_modules/node-cache/lib/node_cache.js:12:59)
    at /Users/john/dev/rasa/rasaui/server/routes/middleware.js:208:23
    at tryCatcher (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
rasa_response:+++ {"entities": [], "intent": {"confidence": 0.9198145520258671, "name": "restaurant_search"}, "text": "restaurant", "intent_ranking": [{"confidence": 0.9198145520258671, "name": "restaurant_search"}, {"confidence": 0.0423096893794707, "name": "greet"}, {"confidence": 0.024086556299309118, "name": "goodbye"}, {"confidence": 0.013789202295352885, "name": "affirm"}]}
No intent Data found. Respond back with Rasa NLU only
Exception while inserting Parse log
Error: Property 'agent_id' doesn't exist.
    at query.replace.name (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:135:19)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.formatAs.object (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:119:22)
    at Object.$formatQuery [as formatQuery] (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:252:29)
    at Database.$query (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/query.js:115:41)
    at Database.<anonymous> (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/query.js:231:23)
    at config.$npm.connect.pool.then.db (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/database.js:242:42)
    at tryCatcher (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
`

<img width="372" alt="screen shot 2017-11-01 at 17 50 50" src="https://user-images.githubusercontent.com/273591/32288892-3991e2cc-bf2d-11e7-94e6-dc47bdc44dbc.png">

**Comment by pradeepmvn** [comment]
It is unable to communicate to the database or the tables doesn't exist.
Was the result of script execution successful? (https://github.com/paschmann/rasa-ui/blob/master/resources/dbcreate.sql)

**Comment by johngriffin** [comment]
Ah, I recreated the database and reimported dbcreate.sql and I see in the middle of a load of successful looking output the following error:

```
CREATE TABLE
/* Views */
CREATE OR REPLACE VIEW public.intents_most_used AS
select intent_name, agents.agent_id, agents.agent_name, grouped_intents.grp_intent_count from intents
left outer join (select count(*) as grp_intent_count, intent_name as grp_intent,agent_id as grp_agent_id from nlu_parse_log
group by (intent_name,agent_id)) as grouped_intents
on intent_name = grouped_intents.grp_intent, agents where intents.agent_id=agents.agent_id  order by agents.agent_id;
psql:./resources/dbcreate.sql:299: ERROR:  column "nlu_parse_log.intent_name" must appear in the GROUP BY clause or be used in an aggregate function
```

I'm using Postgres v9.5 locally which is not that old and I'd rather not upgrade as I have a few other databases I'd need to migrate.  Do you know if I need to upgrade to a particular version in order for this to work?

**Comment by pradeepmvn** [comment]
I have tested in 9.6 version. That particular query ran for me fine. But I updated it to more specific joins following the error. Can you delete the DB and re-run the dbcreate.sql (https://github.com/paschmann/rasa-ui/blob/master/resources/dbcreate.sql)

**Comment by johngriffin** [comment]
Hi @pradeepmvn  - thanks for updating the join, that seems to have fixed the error I was getting when running dbcreate.sql against postgres 9.5.

I'm still getting the error in the terminal though when I run the query in the RH pane that's in the screenshot above.  It seems to return the correct info in the UI.

`Rasa NLU Parse Request -> http://localhost:5000/parse
Create Initial cache
Object Inserted into Cache
Agent Information: []
DB Error while getting agent details.
TypeError: Cannot read property 'agent_id' of undefined
    at /Users/john/dev/rasa/rasaui/server/routes/middleware.js:215:48
    at NodeCache.module.exports.NodeCache.get (/Users/john/dev/rasa/rasaui/node_modules/node-cache/lib/node_cache.js:101:11)
    at NodeCache.get (/Users/john/dev/rasa/rasaui/node_modules/node-cache/lib/node_cache.js:12:59)
    at /Users/john/dev/rasa/rasaui/server/routes/middleware.js:208:23
    at tryCatcher (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
rasa_response:+++ {"entities": [], "intent": {"confidence": 0.38860473781418303, "name": "goodbye"}, "text": "test", "intent_ranking": [{"confidence": 0.38860473781418303, "name": "goodbye"}, {"confidence": 0.38203966889948204, "name": "restaurant_search"}, {"confidence": 0.14964142422876064, "name": "greet"}, {"confidence": 0.07971416905757406, "name": "affirm"}]}
No intent Data found. Respond back with Rasa NLU only
Exception while inserting Parse log
Error: Property 'agent_id' doesn't exist.
    at query.replace.name (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:135:19)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.formatAs.object (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:119:22)
    at Object.$formatQuery [as formatQuery] (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/formatting.js:252:29)
    at Database.$query (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/query.js:115:41)
    at Database.<anonymous> (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/query.js:231:23)
    at config.$npm.connect.pool.then.db (/Users/john/dev/rasa/rasaui/node_modules/pg-promise/lib/database.js:242:42)
    at tryCatcher (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/john/dev/rasa/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)`

**Comment by vitaly-t** [comment]
`Property 'agent_id' doesn't exist` - comes from method `query` of `pg-promise` when you are using the property in your query, while the parameters are missing the property completely.

**Comment by pradeepmvn** [comment]
@johngriffin Thanks for your input..Good that it's working for you. Agent in the rasa-ui is equal to Project in rasa_nlu. In the Parse query make sure you pass the Project parameter which will be used to log the parse requests. Without it, the parse requests will silently fail and log this error. Iam closing this for now, please open another if there is any other issue.
