### ISSUE TITLE
training  fails since rasa_nlu expects data in json file

### ISSUE THREAD

**Issue by NagarajGond** [paschmann/rasa-ui#3]
Able to add the intents under agents screen, but couldn't link intents and entities ( another issue anyway).

training fails with below error. Let me know any configuration changes required to get rid of this error.
rasa_nlu ver:  0.9.0a3

postgrest up and running

started rasa server as:
python -m rasa_nlu.server &

```
POST: /train?model=production -> http://rasahost:5000/train?model=production
INFO:rasa_nlu.data_router:Starting model training
[12/Jun/2017:00:25:25 -0700] "POST /nlu_log HTTP/1.1" 201 - "" ""
INFO:rasa_nlu.data_router:Training process <Process(Process-2, started)> started
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
[2017-06-12 00:25:25] "POST /train?model=production HTTP/1.1" 200 185 0.014566
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "rasa_nlu/train.py", line 73, in do_train
    training_data = load_data(config['data'])
  File "rasa_nlu/converters.py", line 255, in load_data
    fformat = guess_format(files)
  File "rasa_nlu/converters.py", line 225, in guess_format
    file_data = json.loads(f.read())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
GET: /status -> http://rasahost:5000/status
```

**Comment by paschmann** [comment]
Hi @NagarajGond - thanks for bring this up. Are you seeing data when you select your specific model? e.g. 
![image](https://user-images.githubusercontent.com/4396042/27054774-fa0a8e5e-4f76-11e7-857d-10f90517b37d.png)

**Comment by paschmann** [comment]
@NagarajGond - please could you post your "pipeline" value from your config file. I seemed to get a similar error when I specified "all_components"

**Comment by NagarajGond** [comment]
sorry for the delay.

now I'm able to train the model after starting the server as below but I couldn't select the new created model under Agents tab.: 

python -m rasa_nlu.server -c config_mitie.json

config_mitie.json file:
```
{
  "pipeline": "mitie",
  "mitie_file": "./data/total_word_feature_extractor.dat",
  "path" : "./models",
  "data" : "./data/train-rasa.json",
  "server_model_dirs" : "model_20170523-005847"
}
```


What I'm trying to do/looking from this UI:

1.  Provide option to choose pipeline for training.
2.  Allow to change the config to use newly created model and restart server.
3. Option to import existing training json to database so that all the old intents will be available under Agents tab.

**Comment by paschmann** [comment]
Hi @NagarajGond - thanks for the comments and feedback, this is helpful. 

With regards to your requests, they are all valid and interesting. I agree that having this ability would also be helpful but would require some changes to Rasa NLU itself to support these use cases. I will add them to the roadmap.

**Comment by overlordxxx** [comment]
Attached is a copy of a log file.   Could the problem be that the data is not formatted as a json array?  (i.e. "[ {json}, {json}, {json} ]" ).

[rasa_nlu_log-20170921-132249-4354 copy.txt](https://github.com/paschmann/rasa-ui/files/1322518/rasa_nlu_log-20170921-132249-4354.copy.txt)
