### ISSUE TITLE
Passthrough parse URL does not have the same behaviour as requesting a parse from RASA Core directly

### ISSUE THREAD

**Issue by saikojosh** [paschmann/rasa-ui#44]
A request to  RASA Core at `http://localhost:7000/parse?q=hello%20there` returns this data:

```
{
  "entities": [],
  "intent": {
    "confidence": 1.0,
    "name": "greet"
  },
  "text": "hello there"
}
```

Whereas a request via the RASA UI parse middleware at `http://localhost:7001/api/v2/rasa/parse?q=hello%20there` returns this:

```
{
    "error": "Exception caught !!"
}
```

AND throws an error!

```
rasa-ui_1   | Rasa NLU Parse Request -> http://rasa-core:7000/parse
rasa-ui_1   | Create Initial cache
rasa-ui_1   | Object Inserted into Cache
rasa-ui_1   | rasa_response:+++ {
rasa-ui_1   |   "error": "Invalid parse parameter specified"
rasa-ui_1   | }
rasa-ui_1   | TypeError: Cannot read property 'name' of undefined
rasa-ui_1   |     at /usr/src/app/server/routes/middleware.js:165:59
rasa-ui_1   |     at NodeCache.module.exports.NodeCache.get (/usr/src/app/node_modules/node-cache/lib/node_cache.js:101:11)
rasa-ui_1   |     at NodeCache.get (/usr/src/app/node_modules/node-cache/lib/node_cache.js:12:59)
rasa-ui_1   |     at updateCacheWithRasaNluResponse (/usr/src/app/server/routes/middleware.js:158:17)
rasa-ui_1   |     at Request._callback (/usr/src/app/server/routes/middleware.js:105:7)
rasa-ui_1   |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:186:22)
rasa-ui_1   |     at emitTwo (events.js:106:13)
rasa-ui_1   |     at Request.emit (events.js:191:7)
rasa-ui_1   |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1163:10)
rasa-ui_1   |     at emitOne (events.js:96:13)
rasa-ui_1   |     at Request.emit (events.js:188:7)
rasa-ui_1   |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1085:12)
rasa-ui_1   |     at IncomingMessage.g (events.js:292:16)
rasa-ui_1   |     at emitNone (events.js:91:20)
rasa-ui_1   |     at IncomingMessage.emit (events.js:185:7)
rasa-ui_1   |     at endReadableNT (_stream_readable.js:974:12)
rasa-ui_1   | DB Error while getting agent details.
rasa-ui_1   | { error: there is no parameter $1
rasa-ui_1   |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:539:11)
rasa-ui_1   |     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:366:17)
rasa-ui_1   |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:105:22)
rasa-ui_1   |     at emitOne (events.js:96:13)
rasa-ui_1   |     at Socket.emit (events.js:188:7)
rasa-ui_1   |     at readableAddChunk (_stream_readable.js:176:18)
rasa-ui_1   |     at Socket.Readable.push (_stream_readable.js:134:10)
rasa-ui_1   |     at TCP.onread (net.js:559:20)
rasa-ui_1   |   name: 'error',
rasa-ui_1   |   length: 94,
rasa-ui_1   |   severity: 'ERROR',
rasa-ui_1   |   code: '42P02',
rasa-ui_1   |   detail: undefined,
rasa-ui_1   |   hint: undefined,
rasa-ui_1   |   position: '41',
rasa-ui_1   |   internalPosition: undefined,
rasa-ui_1   |   internalQuery: undefined,
rasa-ui_1   |   where: undefined,
rasa-ui_1   |   schema: undefined,
rasa-ui_1   |   table: undefined,
rasa-ui_1   |   column: undefined,
rasa-ui_1   |   dataType: undefined,
rasa-ui_1   |   constraint: undefined,
rasa-ui_1   |   file: 'parse_expr.c',
rasa-ui_1   |   line: '824',
rasa-ui_1   |   routine: 'transformParamRef' }
```

Surely the behaviour should be identical between the two?

**Comment by paschmann** [comment]
Hi @saikojosh - this should be resolved with the latest commit
