### ISSUE TITLE
Rasa Chat error

### ISSUE THREAD

**Issue by karthikbalu** [paschmann/rasa-ui#64]
Chat window not responding the throws following error in the server backend

Got an action of utter type. Fetching info from db
Error occurred. Respond back with Rasa NLU only
Error occurred. Respond back with Rasa NLU only
ReferenceError: err is not defined
    at /Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/mw_routes/core_router.js:249:20
    at tryCatcher (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

also below error

DB Error while getting agent details.
TypeError: Cannot read property 'rasa_core_enabled' of undefined
    at routeRequest (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/middleware.js:43:16)
    at /Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/middleware.js:32:7
    at tryCatcher (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by ayashjorden** [comment]
@karthikbalu , when rasaui app is loading, does it show a successfull connection to the DB?
example:
```
Postgres DB Connected
Using connection string from: package.json
Postgres Server: 172.17.0.2:5432
Database:rasaui
Schema:public
```

**Comment by karthikbalu** [comment]
yes

Rasa UI Server: http://localhost:5001

Express server listening on port 5001

Rasa NLU Connected
Using connection string from: package.json
Rasa NLU Server: http://localhost:5004


Rasa Core Connected
Using connection string from: package.json
Rasa Core Server: http://localhost:5005


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:rasaui
Schema:public

**Comment by karthikbalu** [comment]
No Token, but got an Auth request. Allowing it
Authenticate User
Rasa NLU Status Request -> http://localhost:5004/status
Rasa NLU Version Request -> http://localhost:5004/version
settings.getSettings
Rasa NLU Status Request -> http://localhost:5004/status
Rasa NLU Config Request -> http://localhost:5004/config
Got to parse middleware
Cache Not Found for Agent. Making a DB call for: clofusbot
Agent Information: []
DB Error while getting agent details.
TypeError: Cannot read property 'rasa_core_enabled' of undefined
    at routeRequest (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/middleware.js:43:16)
    at /Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/middleware.js:32:7
    at tryCatcher (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Got to parse middleware
Cache Not Found for Agent. Making a DB call for: clofus
Agent Information: [{"agent_id":1,"agent_name":"clofus","endpoint_enabled":false,"endpoint_url":null,"basic_auth_username":"admin","basic_auth_password":"admin","rasa_core_enabled":true}]
Rasa Core Parse Request -> http://localhost:5005/conversations/admin/parse
Create Initial cache for rasa Core Parse Request
After request:{"next_action": "utter_hi", "tracker": {"sender_id": "admin", "slots": {"cuisine": null, "matches": null}, "latest_message": {"intent": {"name": "greet", "confidence": 0.14112411263389862}, "entities": [], "intent_ranking": [{"name": "greet", "confidence": 0.14112411263389862}, {"name": "clofus_exclamation", "confidence": 0.07309127466825298}, {"name": "are_we_friends", "confidence": 0.0407103315283429}, {"name": "clofus_bye", "confidence": 0.03611548804431702}, {"name": "thank_you", "confidence": 0.03406156390588131}, {"name": "you_are_welcome", "confidence": 0.03301081745902056}, {"name": "you_are_bad", "confidence": 0.032712847530855675}, {"name": "confirmation", "confidence": 0.03065388490764292}, {"name": "dont_care", "confidence": 0.02443560822268291}, {"name": "answer_me", "confidence": 0.023677292022909118}], "text": "hi"}, "latest_event_time": 1525026779.499337, "paused": false, "events": null}}
Rasa Core Resonse: {"next_action":"utter_hi","tracker":{"sender_id":"admin","slots":{"cuisine":null,"matches":null},"latest_message":{"intent":{"name":"greet","confidence":0.14112411263389862},"entities":[],"intent_ranking":[{"name":"greet","confidence":0.14112411263389862},{"name":"clofus_exclamation","confidence":0.07309127466825298},{"name":"are_we_friends","confidence":0.0407103315283429},{"name":"clofus_bye","confidence":0.03611548804431702},{"name":"thank_you","confidence":0.03406156390588131},{"name":"you_are_welcome","confidence":0.03301081745902056},{"name":"you_are_bad","confidence":0.032712847530855675},{"name":"confirmation","confidence":0.03065388490764292},{"name":"dont_care","confidence":0.02443560822268291},{"name":"answer_me","confidence":0.023677292022909118}],"text":"hi"},"latest_event_time":1525026779.499337,"paused":false,"events":null}}
Got an action of utter type. Fetching info from db
Error occurred. Respond back with Rasa NLU only
Error occurred. Respond back with Rasa NLU only
ReferenceError: err is not defined
    at /Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/server/routes/mw_routes/core_router.js:249:20
    at tryCatcher (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/karthikbalu/MYDRIVE/DEVELOPMENT/PROTOTYPES/rasa-ui/rasaui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Rasa NLU Status Request -> http://localhost:5004/status
Rasa NLU Config Request -> http://localhost:5004/config

**Comment by pradeepmvn** [comment]
@karthikbalu 
> DB Error while getting agent details.

Is the Agent created in Postgres DB? Can you check that? It looks like there might have been an error when creating an agent it self

**Comment by praneesh12** [comment]
Hi All, 
Can someone please help me figure out what can be possible reasons for the connection error in rasa_nlu and rasa_core. I'm getting the following result on executing npm start in rasaui folder.

RasaUI@0.2.0 start /home/praneesh/chatbot/rasa-ui
node server/server.js

Rasa UI Server: http://localhost:5001
Express server listening on port 5001

Rasa NLU Error: Error: connect ECONNREFUSED 127.0.0.1:5000
Using connection string from: package.json

Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005
Using connection string from: package.json


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:rasaui
Schema:public

I have updated the package.json file. Here is the configuration attribute of the file. 
"config": {
    "rasanluendpoint": "http://localhost:5000",
    "rasacoreendpoint": "http://localhost:5005",
    "coresecuritytoken": "",
    "nlusecuritytoken": "",
    "cacheagents": false,
    "jwtsecret": "th1s1sn0t0nlyths3cr3tbutth3m0st1mp0rtAntp13c30f1nf0rmAt10nf0rth1sAppl1cAt10n",
    "postgresserver": "postgres://*****:*****@localhost:5432/rasaui"
}

Please let me know how can I fix this issue.

**Comment by pradeepmvn** [comment]
@praneesh12 please check the configuration in package.json. That should be picked up at the startup of the server. Please open another issue if it still persists.
