### ISSUE TITLE
builtins.AttributeError: 'RasaCoreServer' object has no attribute 'access_token'

### ISSUE THREAD

**Issue by ayashjorden** [paschmann/rasa-ui#65]
Hello,
When I try the conversation sidebar (in the Agent screen), it causes my Rasa core (HTTP server) to throw an exception and crash the rasaui server.

I'm running RASA NLU as HTTP server and CORE as HTTP server based on the provided script from the Training section -> 'Rasa Core Config' sub section python script:
```
import logging
from rasa_core.interpreter import RasaNLUHttpInterpreter
from rasa_core.server import RasaCoreServer
from rasa_core.server import create_argument_parser

logger = logging.getLogger(__name__)

if __name__ == '__main__':
    # Script to run Rasa NLU HTTP Interpreter
    arg_parser = create_argument_parser()
    cmdline_args = arg_parser.parse_args()

    logging.basicConfig(level=cmdline_args.loglevel)
    if cmdline_args.nlu == 'RasaNLUHttpInterpreter':
        logger.info("Creating RasaNLU HTTP Interpreter")
        # Fill in the modelname and server details.
        cmdline_args.nlu = RasaNLUHttpInterpreter(model_name="MODEL_NAME",
                                                  token="",
                                                  server="http://localhost:5000",
                                                  project_name="PROJECT_NAME")

    rasa = RasaCoreServer(cmdline_args.core,
                          cmdline_args.nlu,
                          cmdline_args.loglevel,
                          cmdline_args.log_file,
                          cmdline_args.cors,
                          auth_token=cmdline_args.auth_token)

    logger.info("Starting Rasa Core http server on port %s" %
                cmdline_args.port)
    rasa.app.run("0.0.0.0", cmdline_args.port)
```
rasaui error:
```
HTML_OF_THE_PYTHON_STACK_TRACE_BELOW

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/Users/jbar/private-src/rasaui/server/routes/mw_routes/core_router.js:109:24)
    at Request.self.callback (/Users/jbar/private-src/rasaui/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/Users/jbar/private-src/rasaui/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/Users/jbar/private-src/rasaui/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)

```

```
2018-04-28 15:37:38+0300 [_GenericHTTPChannelProtocol,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/twisted/web/server.py", line 255, in render
	    body = resrc.render(self)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/klein/resource.py", line 210, in render
	    d = defer.maybeDeferred(_execute)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/klein/resource.py", line 204, in _execute
	    **kwargs)
	--- <exception caught here> ---
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/klein/app.py", line 128, in execute_endpoint
	    return endpoint_f(self._instance, *args, **kwargs)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/klein/app.py", line 227, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/klein/app.py", line 50, in _call
	    result = f(*args, **kwargs)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/rasa_nlu/server.py", line 108, in decorated
	    return f(*args, **kwargs)
	  File "$HOME/venv/PROJECT_DIR/lib/python3.6/site-packages/rasa_nlu/server.py", line 124, in decorated
	    if self.access_token is None or token == self.access_token:
	builtins.AttributeError: 'RasaCoreServer' object has no attribute 'access_token'
```

Thank you,
Jorden

**Comment by ayashjorden** [comment]
Issue is gone when installed `rasa_core==0.9.0a3` and `rasa_nlu==0.12.2`
