### ISSUE TITLE
Side chat in agent section cause RASA NLU to throw AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ayashjorden** [paschmann/rasa-ui#66]
Hi,
After training a new model, trying to use the side chat in the Agent screen causes RASA NLU HTTP server to throw the below exception.

Appreciate any insight/solution

Thank you in advance,
Yarden

```
2018-05-02 00:43:25+0300 [-] 2018-05-02 00:43:25 ERROR    __main__ - 'str' object has no attribute 'get'
2018-05-02 00:43:25+0300 [-] Traceback (most recent call last):
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/server.py", line 232, in parse
2018-05-02 00:43:25+0300 [-]     else threads.deferToThread(self.data_router.parse, data))
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2018-05-02 00:43:25+0300 [-]     result = inContext.theWork()
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2018-05-02 00:43:25+0300 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2018-05-02 00:43:25+0300 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2018-05-02 00:43:25+0300 [-]     return func(*args,**kw)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 237, in parse
2018-05-02 00:43:25+0300 [-]     model)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/project.py", line 118, in parse
2018-05-02 00:43:25+0300 [-]     interpreter = self._interpreter_for_model(model_name)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/project.py", line 177, in _interpreter_for_model
2018-05-02 00:43:25+0300 [-]     return Interpreter.create(metadata, self._component_builder)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/model.py", line 298, in create
2018-05-02 00:43:25+0300 [-]     components.validate_requirements(model_metadata.component_classes)
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/model.py", line 85, in component_classes
2018-05-02 00:43:25+0300 [-]     return [c.get("class") for c in self.get('pipeline', [])]
2018-05-02 00:43:25+0300 [-]   File "$HOME/venv/PROJECT_NAME/lib/python3.6/site-packages/rasa_nlu/model.py", line 85, in <listcomp>
2018-05-02 00:43:25+0300 [-]     return [c.get("class") for c in self.get('pipeline', [])]
2018-05-02 00:43:25+0300 [-] AttributeError: 'str' object has no attribute 'get'
```

**Comment by tmbo** [comment]
This looks like an invalid configuration is used to train the NLU model. With "invalid" I mean a configuration of the old format using "pipeline: ["componentA", "componentB"]" instead of 

```yaml
pipeline:
- name: componentA
- name: componentB
```

**Comment by ayashjorden** [comment]
The issue persists.

Rasa NLU command:
`LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 ~/venv/cubics-bot/bin/python -m rasa_nlu.server -c ./config_spacy.yaml --path `pwd`/models/nlu`

NLU config file:
```
project: "cubics.fm"
pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_spacy"
  - name: "intent_entity_featurizer_regex"
  - name: "intent_featurizer_spacy"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_classifier_sklearn"
  - name: "ner_spacy"
path: "./models/nlu"
port: 5000
data: "./data/cubics-fm-small.json"
language: "en"
log_level: "DEBUG"
fixed_model_name: "cubics_support"
```

Steps taken:
1. Train Rasa NLU using Rasa-UI training section
2. In Agent section
2.1 Select the newly trained model
2.2 Start a conversation on the chat on the right side

NLU logs:
```
2018-05-26 00:56:00+0300 [-] 2018-05-26 00:56:00 ERROR    __main__ - 'str' object has no attribute 'get'
2018-05-26 00:56:00+0300 [-] Traceback (most recent call last):
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/server.py", line 232, in parse
2018-05-26 00:56:00+0300 [-]     else threads.deferToThread(self.data_router.parse, data))
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2018-05-26 00:56:00+0300 [-]     result = inContext.theWork()
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2018-05-26 00:56:00+0300 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2018-05-26 00:56:00+0300 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2018-05-26 00:56:00+0300 [-]     return func(*args,**kw)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 237, in parse
2018-05-26 00:56:00+0300 [-]     model)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/project.py", line 118, in parse
2018-05-26 00:56:00+0300 [-]     interpreter = self._interpreter_for_model(model_name)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/project.py", line 177, in _interpreter_for_model
2018-05-26 00:56:00+0300 [-]     return Interpreter.create(metadata, self._component_builder)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/model.py", line 298, in create
2018-05-26 00:56:00+0300 [-]     components.validate_requirements(model_metadata.component_classes)
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/model.py", line 85, in component_classes
2018-05-26 00:56:00+0300 [-]     return [c.get("class") for c in self.get('pipeline', [])]
2018-05-26 00:56:00+0300 [-]   File "PYTHON_VENV/cubics-bot/lib/python3.6/site-packages/rasa_nlu/model.py", line 85, in <listcomp>
2018-05-26 00:56:00+0300 [-]     return [c.get("class") for c in self.get('pipeline', [])]
2018-05-26 00:56:00+0300 [-] AttributeError: 'str' object has no attribute 'get'
```

Rasa versions:
```
rasa-core==0.9.0a3
rasa-nlu==0.12.2
```

Appreciate your help,
Jorden

**Comment by ayashjorden** [comment]
@tmbo any other idea?
