### ISSUE TITLE
Failed to instantiate module app

### ISSUE THREAD

**Issue by franticBIT** [paschmann/rasa-ui#73]
Hi,  
I'm currently trying to run rasa-ui as a Docker container.  
When I visit the login page, the login form is displayed, but I get the following error on the console:
```
Failed to instantiate module app due to:
Error: [$injector:modulerr] http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=n...)
    at http://localhost:5001/scripts/angular/angular.min.js:6:425
    at http://localhost:5001/scripts/angular/angular.min.js:42:407
    at q (http://localhost:5001/scripts/angular/angular.min.js:7:495)
    at g (http://localhost:5001/scripts/angular/angular.min.js:41:476)
    at http://localhost:5001/scripts/angular/angular.min.js:42:149
    at q (http://localhost:5001/scripts/angular/angular.min.js:7:495)
    at g (http://localhost:5001/scripts/angular/angular.min.js:41:476)
    at eb (http://localhost:5001/scripts/angular/angular.min.js:46:44)
    at c (http://localhost:5001/scripts/angular/angular.min.js:21:373)
    at Sc (http://localhost:5001/scripts/angular/angular.min.js:22:179
```
I tried using the image from Docker Hub as well as building it from the GitHub repo.

**Comment by yuxuan2015** [comment]
https://github.com/paschmann/rasa-ui/issues/78

**Comment by pradeepmvn** [comment]
Latest image and master should fix this. Please reopen if it still exists.
