### ISSUE TITLE
Unable to start the rasa UI

### ISSUE THREAD

**Issue by harshitazilen** [paschmann/rasa-ui#76]
I face below error while starting the software. Please find attached file for debugging info.

```
> RasaUI@0.2.0 start /home/harshit/Downloads/RasaUI/rasaui
> node server/server.js

## There is an issue with `node-fibers` ##
`/home/harshit/Downloads/RasaUI/rasaui/node_modules/fibers/bin/linux-x64-64/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /home/harshit/Downloads/RasaUI/rasaui/node_modules/fibers/build
/home/harshit/Downloads/RasaUI/rasaui/node_modules/fibers/fibers.js:20
	throw new Error('Missing binary. See message above.');
	^

Error: Missing binary. See message above.
    at Object.<anonymous> (/home/harshit/Downloads/RasaUI/rasaui/node_modules/fibers/fibers.js:20:8)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/harshit/Downloads/RasaUI/rasaui/node_modules/asyncawait/src/fibers.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)

npm ERR! Linux 4.4.0-124-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! RasaUI@0.2.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RasaUI@0.2.0 start script 'node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the RasaUI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs RasaUI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls RasaUI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     [/home/harshit/Downloads/RasaUI/rasaui/npm-debug.log]

[npm-debug.log](https://github.com/paschmann/rasa-ui/files/2026232/npm-debug.log)

```

**Comment by harshitazilen** [comment]
I am using v10 of node js.  Please find below terminal output

```
harshit@harshit-G41MT-S2:~/Downloads/RasaUI/rasaui$ node -v
v10.1.0
```

**Comment by yuxuan2015** [comment]
@harshitazilen Has your problem been solved?

**Comment by harshitazilen** [comment]
@yuxuan2015 , no It is still there. I am unable to start.

**Comment by yuxuan2015** [comment]
Is linux-x64-64 in your directory, my directory is linux-x64-46?

**Comment by harshitazilen** [comment]
I could find below directories

linux-x64-46
linux-x64-48
linux-ia32-46
linux-ia32-48

**Comment by yuxuan2015** [comment]
@pradeepmvn My directory  is linux-x64-46,not linux-x64-64.Do you know what happend?

**Comment by yuxuan2015** [comment]
@harshitazilen https://github.com/clofus/clofus-chatbot,another rasa-UI

**Comment by pradeepmvn** [comment]
This is particular to node v10 with fibers module. I was able to reporoduce it. Temporary solution would be to roll back to node V9 and do npm install. I tested this and works fine.
