### ISSUE TITLE
Login Angular injector error 

### ISSUE THREAD

**Issue by RSginer** [paschmann/rasa-ui#78]
I can't login in the web app because it throws the following error:

![captura de pantalla de 2018-05-27 13-47-06](https://user-images.githubusercontent.com/14939307/40585520-a2979d64-61b4-11e8-9b1b-db685013d5f5.png)

I have runing the dockers of rasa nlu and rasa core in 5005 and 5000 ports and in the docker of rasa-ui i has already specified

Error:

`jquery.min.js:2 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=app&p1=Error: [$injector:modulerr] http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=ngSanitize&p1=TypeError: q is not a function
    at B (http://localhost:5001/scripts/angular-sanitize/angular-sanitize.min.js:6:289)
    at f (http://localhost:5001/scripts/angular-sanitize/angular-sanitize.min.js:6:217)
    at new <anonymous> (http://localhost:5001/scripts/angular-sanitize/angular-sanitize.min.js:13:3)
    at Object.instantiate (http://localhost:5001/scripts/angular/angular.min.js:44:272)
    at c (http://localhost:5001/scripts/angular/angular.min.js:41:187)
    at Object.provider (http://localhost:5001/scripts/angular/angular.min.js:41:129)
    at d (http://localhost:5001/scripts/angular/angular.min.js:42:64)
    at http://localhost:5001/scripts/angular/angular.min.js:42:185
    at q (http://localhost:5001/scripts/angular/angular.min.js:7:495)
    at g (http://localhost:5001/scripts/angular/angular.min.js:41:476)
    at http://localhost:5001/scripts/angular/angular.min.js:6:425
    at http://localhost:5001/scripts/angular/angular.min.js:42:407
    at q (http://localhost:5001/scripts/angular/angular.min.js:7:495)
    at g (http://localhost:5001/scripts/angular/angular.min.js:41:476)
    at http://localhost:5001/scripts/angular/angular.min.js:42:149
    at q (http://localhost:5001/scripts/angular/angular.min.js:7:495)
    at g (http://localhost:5001/scripts/angular/angular.min.js:41:476)
    at eb (http://localhost:5001/scripts/angular/angular.min.js:46:44)
    at c (http://localhost:5001/scripts/angular/angular.min.js:21:373)
    at Sc (http://localhost:5001/scripts/angular/angular.min.js:22:179) at angular.js:38 at angular.js:4920 at q (angular.js:403) at g (angular.js:4880) at eb (angular.js:4802) at c (angular.js:1914) at Sc (angular.js:1935) at ue (angular.js:1820) at HTMLDocument.<anonymous> (angular.js:33367) at j (jquery.min.js:2)`

My package:

`"config": {
    "rasanluendpoint": "http://localhost:5000",
    "rasacoreendpoint": "http://localhost:5005",
    "coresecuritytoken": "",
    "nlusecuritytoken": "",
    "cacheagents": false,
    "jwtsecret": "th1s1sn0t0nlyths3cr3tbutth3m0st1mp0rtAntp13c30f1nf0rmAt10nf0rth1sAppl1cAt10n",
    "postgresserver": "/var/run/postgresql"
  },
`

**Comment by daniyuu** [comment]
I met this issue too.

Here is my fix:

'''index.html''' replace the package of angular-sanitize, like this:


<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-sanitize.js"></script>
  
It works for me.

**Comment by RSginer** [comment]
@beevelop yes is with the latest image

**Comment by binderchri** [comment]
Another solution/fix than the one suggested by @daniyuu is by adding circumflex wildcards to `angular`, `angular-resource` and `angular-route` in package.json (see: https://github.com/binderchri/rasa-ui/commit/728fa270155dedcd44e86cf4ef3cb2ba69bbca64)

**Comment by pradeepmvn** [comment]
I am working on updating the image and repo to point to node version:10.

**Comment by pradeepmvn** [comment]
The current images( on node 6) worked fine.
Latest master is tested against, node 9 and 10 no issues were found.
