### ISSUE TITLE
how to set up on windows?

### ISSUE THREAD

**Issue by ctrado18** [paschmann/rasa-ui#82]
I tried to install Rasa Ui within a conda virtual enivornment with python 3.6 and get:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Anaconda3\envs\env1\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:184:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\chris1\rasaui\node_modules\fibers
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
Der Befehl "nodejs" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2018-06-13T15_14_51_719Z-debug.log
```

What do I have to do for windows?

**Comment by pradeepmvn** [comment]
@ctrado18 There are no specific instructions for Windows. The only prerequisite is to have correct version( Windows) of nodejs.
There is an error #76 for node v10 specifically with Fibers module. This should be related to that as well.

**Comment by ctrado18** [comment]
@pradeepmvn So I should use node 9? I will try that! Also, the first errors are related to the python. exe and env variable. Should I care about this since I am working in a conda virtual environment?

Thank you!

**Comment by pradeepmvn** [comment]
@ctrado18 There is no need to work in Anaconda Env. Since this used node and node adds some global dependencies, I would strongly recommend trying outside of Anaconda., just on a plain command prompt. Also, the latest master has a fix for node v10. Please try that.

**Comment by abhoyar** [comment]
@pradeepmvn  I'm trying to install rasa ui in my win7 machine which has vs2015 and anaconda 3.6.
I followed the reference from this link for installation but didn't woked out for me.
[http://www.toptechpoint.com/mlai/rasa-nlu-ui-configuration-installation
]
Here is the error screen shot attached for reference. 
![rasaui issue](https://user-images.githubusercontent.com/7037022/42894082-9c74fa24-8ad3-11e8-91fa-f394a31ed2ee.PNG)

**Comment by ctrado18** [comment]
I tried latest master with v10. Still there are node problems:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:184:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\\rasaui\node_modules\fibers
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
Der Befehl "nodejs" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\\AppData\Roaming\npm-cache\_logs\2018-08-09T15_50_49_125Z-debug.log
```
