### ISSUE TITLE
It throws TypeError when I use the side chat in the Agent screen

### ISSUE THREAD

**Issue by windyjune** [paschmann/rasa-ui#83]
Hi,
   I trained a rasa_nlu model, and start the rasa_nlu server. Then I want test my sample using the side chat in the Agent screen. It doesn't work and throws a TypeError.

'''
Cache Not Found for Agent. Making a DB call for: default
Agent Information: []
DB Error while getting agent details.
TypeError: Cannot read property 'agent_id' of undefined
    at /home/vagrant/zhujh/rasa-ui/server/routes/middleware.js:41:36
    at tryCatcher (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/vagrant/zhujh/rasa-ui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

'''

**Comment by pradeepmvn** [comment]
Did you train it from rasa-ui? 
> I trained a rasa_nlu model
Error says no Agent found in the DB.  If you trained a model with in Rasa_NLU and didnt use UI, you have to create an agent in RASA UI and select it from the drop down to work.

**Comment by windyjune** [comment]
Yes, I trained the model in Rasa_NLU.  But I created an agent in RASA UI and selected it from the drop down,  and I found the agent in `agents` Table  in the DB.  I don't know why the error says no agent in DB.

**Comment by windyjune** [comment]
It is ok now. It is caused by the name of Agent not same as the project name of the model.

**Comment by pradeepmvn** [comment]
ok great.
