### ISSUE TITLE
Installation error in archlinux

### ISSUE THREAD

**Issue by NicoHood** [paschmann/rasa-ui#97]
npm install fails on my arch linux system:
```
make: *** [fibers.target.mk:108: Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory '/home/arch/hackallthethings/partybot/rasa-ui/node_modules/fibers/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.17.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/arch/hackallthethings/partybot/rasa-ui/node_modules/fibers
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arch/.npm/_logs/2018-07-29T16_24_18_492Z-debug.log
```

I assume that this is because I am using nodejs 10.6.0 and fibers 1.0.15 (2 years old!) does not support V8. Could you please upgrade to a more recent version?

**Comment by haibinzero** [comment]
Hi I can provide a WR here.
npm install fibers in another directory,  then move the hole fibers into where reports this error(/home/arch/hackallthethings/partybot/rasa-ui/node_modules/fibers).
Could someone give an official way for this issue?

**Comment by pradeepmvn** [comment]
@NicoHood This is not a direct reference to the project. Asyncawait package brings in the fibers. Looks like there is a new version of asyncawait(1.0.7). Let me upgrade the project to it and test it.

**Comment by NicoHood** [comment]
Seems to build now, but I get security warnings:
```
added 13 packages from 41 contributors, removed 2 packages, updated 14 packages and audited 522 packages in 7.678s
found 12 vulnerabilities (2 low, 9 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
